### ISSUE TITLE
Error of failed building when using --pep8 in .travis.yml 

### ISSUE THREAD

**Issue by nicole-molino** [Duke-BME-Design/unit-testing-nicole-molino#5]
When using CI, I am getting an error for failed building from Travis. It works correctly when the I only include -pytest -v, but now when I include -pytest -v --pep8.

**Comment by mlp6** [comment]
This is due to what I mention in Issue #4 !  You can remove that `__pycache__` directory using `git rm -r __pycache__` from the root level of the repository, commit that, and then see if it works.

**Comment by nicole-molino** [comment]
@mlp6  Thank you. I will try this. And out of curiosity, I didn't manually create __pycache__ directory. Should I have deleted it from the repository locally? Or just not committed it to GitHub?

**Comment by nicole-molino** [comment]
Fixed, thank you for your help. I removed __pychache__ directory and the env from the repository
